document.body.style.backgroundColor = "#696969";
const Colored = document.querySelector('.page');
Colored.style['background-color'] = 'ghostwhite';
const Span = document.querySelector('.name');
Span.innerHTML = "DJ Rashad";
const Img = document.querySelector('img');
Img.src = "https://thumbnailer.mixcloud.com/unsafe/900x900/extaudio/9/8/b/c/21e8-83e3-4f35-9a95-e6c53ea57bf8.png";
const ShortB = document.querySelector('.short-bio');
ShortB.className += ' animated';