document.body.style.backgroundColor = "#696969";
const colored = document.querySelector('.page');
colored.style['background-color'] = 'ghostwhite';
const span = document.querySelector('.name');
span.innerHTML = "DJ Rashad";
const img = document.querySelector('img');
img.src = "https://thumbnailer.mixcloud.com/unsafe/900x900/extaudio/9/8/b/c/21e8-83e3-4f35-9a95-e6c53ea57bf8.png";
const shortb = document.querySelector('.short-bio');
shortb.className += ' animated';